// Generated by @hypequery/clickhouse
// This file defines TypeScript types based on your ClickHouse database schema

/**
 * Schema interface for use with createQueryBuilder<IntrospectedSchema>()
 * The string literals represent ClickHouse data types for each column
 */
export interface IntrospectedSchema {
  athletes_cache: {
    profile_id: "UInt32";
    name: "String";
    type: "String";
    is_active: "UInt8";
    sport: "String";
    turned_pro_year: "Nullable(UInt16)";
    date_of_birth: "Nullable(Date)";
    nationality: "Nullable(String)";
    nationality_continent: "Nullable(String)";
    football_national_team: "Nullable(String)";
    football_position: "Nullable(String)";
    football_club: "Nullable(String)";
    football_confederation: "Nullable(String)";
    tennis_tour: "Nullable(String)";
    tennis_ranking: "Nullable(UInt32)";
    tennis_playing_style: "Nullable(String)";
    tennis_grand_slams: "Nullable(UInt32)";
    tennis_ranking_points: "Nullable(UInt32)";
    ig_account_id: "Nullable(UInt32)";
    ig_handle: "Nullable(String)";
    ig_followers: "Nullable(Int64)";
    ig_following: "Nullable(Int64)";
    ig_posts: "Nullable(Int64)";
    ig_verified: "Nullable(UInt8)";
    ig_engagement_rate: "Nullable(Float64)";
    tiktok_account_id: "Nullable(UInt32)";
    tiktok_handle: "Nullable(String)";
    tiktok_followers: "Nullable(Int64)";
    tiktok_hearts: "Nullable(Int64)";
    tiktok_videos: "Nullable(Int64)";
    youtube_handle: "Nullable(String)";
    youtube_followers: "Nullable(Int64)";
    twitter_handle: "Nullable(String)";
    twitter_followers: "Nullable(Int64)";
    facebook_handle: "Nullable(String)";
    facebook_followers: "Nullable(Int64)";
    cm_score: "Nullable(Float64)";
    cm_affinity: "Nullable(Float64)";
    last_snapshot_date: "Nullable(Date)";
    created_at: "DateTime";
    modified_at: "DateTime";
    image_url: "Nullable(String)";
    deleted_at: "Nullable(DateTime)";
  };
  cm_artist: {
    id: "Int32";
    name: "String";
    image_url: "String";
    cover_url: "String";
    code2: "String";
    gender: "UInt8";
    isni: "String";
    label: "String";
    record_label: "String";
    is_duplicate: "UInt8";
    band: "UInt8";
    is_non_artist: "UInt8";
    created_at: "Nullable(DateTime)";
    modified_at: "Nullable(DateTime)";
    synced_at: "DateTime";
  };
  profiles: {
    id: "UInt32";
    name: "String";
    profile_type: "String";
    vertical: "String";
    image_url: "Nullable(String)";
    active: "String";
    deleted_at: "Nullable(DateTime)";
    deleted_by: "Nullable(String)";
    created_at: "DateTime";
    updated_at: "DateTime";
    source_id: "Nullable(UInt64)";
  };
}

// Type-safe record types for each table
export interface Athletes_cacheRecord {
  profile_id: number;
  name: string;
  type: string;
  is_active: number;
  sport: string;
  turned_pro_year: number | null;
  date_of_birth: string | null;
  nationality: string | null;
  nationality_continent: string | null;
  football_national_team: string | null;
  football_position: string | null;
  football_club: string | null;
  football_confederation: string | null;
  tennis_tour: string | null;
  tennis_ranking: number | null;
  tennis_playing_style: string | null;
  tennis_grand_slams: number | null;
  tennis_ranking_points: number | null;
  ig_account_id: number | null;
  ig_handle: string | null;
  ig_followers: string | null;
  ig_following: string | null;
  ig_posts: string | null;
  ig_verified: number | null;
  ig_engagement_rate: number | null;
  tiktok_account_id: number | null;
  tiktok_handle: string | null;
  tiktok_followers: string | null;
  tiktok_hearts: string | null;
  tiktok_videos: string | null;
  youtube_handle: string | null;
  youtube_followers: string | null;
  twitter_handle: string | null;
  twitter_followers: string | null;
  facebook_handle: string | null;
  facebook_followers: string | null;
  cm_score: number | null;
  cm_affinity: number | null;
  last_snapshot_date: string | null;
  created_at: string;
  modified_at: string;
  image_url: string | null;
  deleted_at: string | null;
}

export interface Cm_artistRecord {
  id: number;
  name: string;
  image_url: string;
  cover_url: string;
  code2: string;
  gender: number;
  isni: string;
  label: string;
  record_label: string;
  is_duplicate: number;
  band: number;
  is_non_artist: number;
  created_at: string | null;
  modified_at: string | null;
  synced_at: string;
}

export interface ProfilesRecord {
  id: number;
  name: string;
  profile_type: string;
  vertical: string;
  image_url: string | null;
  active: string;
  deleted_at: string | null;
  deleted_by: string | null;
  created_at: string;
  updated_at: string;
  source_id: string | null;
}

/**
 * Usage example:
 *
 * import { createQueryBuilder } from '@hypequery/clickhouse';
 * import { IntrospectedSchema } from './path-to-this-file';
 *
 * // Create a type-safe query builder
 * const db = createQueryBuilder<IntrospectedSchema>();
 *
 * // Now you have full type safety and autocomplete
 * const results = await db
 *   .table('athletes_cache')
 *   .select(['column1', 'column2'])
 *   .where('column1', 'eq', 'value')
 *   .execute();
 */
