// Generated by @hypequery/clickhouse
// This file defines TypeScript types based on your ClickHouse database schema

/**
 * Schema interface for use with createQueryBuilder<IntrospectedSchema>()
 * The string literals represent ClickHouse data types for each column
 */
export interface IntrospectedSchema {
  cm_artist: {
    id: "Int32";
    name: "String";
    image_url: "String";
    cover_url: "String";
    code2: "String";
    gender: "UInt8";
    isni: "String";
    label: "String";
    record_label: "String";
    is_duplicate: "UInt8";
    band: "UInt8";
    is_non_artist: "UInt8";
    created_at: "Nullable(DateTime)";
    modified_at: "Nullable(DateTime)";
    synced_at: "DateTime";
  };
  profiles: {
    id: "UInt32";
    name: "String";
    profile_type: "String";
    vertical: "String";
    image_url: "Nullable(String)";
    active: "String";
    deleted_at: "Nullable(DateTime)";
    deleted_by: "Nullable(String)";
    created_at: "DateTime";
    updated_at: "DateTime";
    source_id: "Nullable(UInt64)";
  };
}

// Type-safe record types for each table
export interface Cm_artistRecord {
  id: number;
  name: string;
  image_url: string;
  cover_url: string;
  code2: string;
  gender: number;
  isni: string;
  label: string;
  record_label: string;
  is_duplicate: number;
  band: number;
  is_non_artist: number;
  created_at: string | null;
  modified_at: string | null;
  synced_at: string;
}

export interface ProfilesRecord {
  id: number;
  name: string;
  profile_type: string;
  vertical: string;
  image_url: string | null;
  active: string;
  deleted_at: string | null;
  deleted_by: string | null;
  created_at: string;
  updated_at: string;
  source_id: string | null;
}

/**
 * Usage example:
 *
 * import { createQueryBuilder } from '@hypequery/clickhouse';
 * import { IntrospectedSchema } from './path-to-this-file';
 *
 * // Create a type-safe query builder
 * const db = createQueryBuilder<IntrospectedSchema>();
 *
 * // Now you have full type safety and autocomplete
 * const results = await db
 *   .table('cm_artist')
 *   .select(['column1', 'column2'])
 *   .where('column1', 'eq', 'value')
 *   .execute();
 */
