// Generated by @hypequery/clickhouse
// This file defines TypeScript types based on your ClickHouse database schema

/**
 * Schema interface for use with createQueryBuilder<IntrospectedSchema>()
 * The string literals represent ClickHouse data types for each column
 */
export interface IntrospectedSchema {
  athletes_cache: {
    profile_id: "UInt32";
    name: "String";
    type: "String";
    is_active: "UInt8";
    sport: "String";
    turned_pro_year: "Nullable(UInt16)";
    date_of_birth: "Nullable(Date)";
    nationality: "Nullable(String)";
    nationality_continent: "Nullable(String)";
    football_national_team: "Nullable(String)";
    football_position: "Nullable(String)";
    football_club: "Nullable(String)";
    football_confederation: "Nullable(String)";
    tennis_tour: "Nullable(String)";
    tennis_ranking: "Nullable(UInt32)";
    tennis_playing_style: "Nullable(String)";
    tennis_grand_slams: "Nullable(UInt32)";
    tennis_ranking_points: "Nullable(UInt32)";
    ig_account_id: "Nullable(UInt32)";
    ig_handle: "Nullable(String)";
    ig_followers: "Nullable(Int64)";
    ig_following: "Nullable(Int64)";
    ig_posts: "Nullable(Int64)";
    ig_verified: "Nullable(UInt8)";
    ig_engagement_rate: "Nullable(Float64)";
    tiktok_account_id: "Nullable(UInt32)";
    tiktok_handle: "Nullable(String)";
    tiktok_followers: "Nullable(Int64)";
    tiktok_hearts: "Nullable(Int64)";
    tiktok_videos: "Nullable(Int64)";
    youtube_handle: "Nullable(String)";
    youtube_followers: "Nullable(Int64)";
    twitter_handle: "Nullable(String)";
    twitter_followers: "Nullable(Int64)";
    facebook_handle: "Nullable(String)";
    facebook_followers: "Nullable(Int64)";
    cm_score: "Nullable(Float64)";
    cm_affinity: "Nullable(Float64)";
    last_snapshot_date: "Nullable(Date)";
    created_at: "DateTime";
    modified_at: "DateTime";
    image_url: "Nullable(String)";
    deleted_at: "Nullable(DateTime)";
  };
  cm_artist: {
    id: "Int32";
    name: "String";
    image_url: "String";
    cover_url: "String";
    code2: "String";
    gender: "UInt8";
    isni: "String";
    label: "String";
    record_label: "String";
    is_duplicate: "UInt8";
    band: "UInt8";
    is_non_artist: "UInt8";
    created_at: "Nullable(DateTime)";
    modified_at: "Nullable(DateTime)";
    synced_at: "DateTime";
  };
  cm_scores: {
    id: "UInt64";
    profile_id: "UInt32";
    profile_type: "String";
    score_date: "Date";
    cm_score: "Float64";
    followers_score: "Float64";
    likes_score: "Float64";
    instagram_followers: "Nullable(Int64)";
    instagram_likes: "Nullable(Int64)";
    tiktok_followers: "Nullable(Int64)";
    tiktok_likes: "Nullable(Int64)";
    youtube_followers: "Nullable(Int64)";
    twitter_followers: "Nullable(Int64)";
    total_followers: "Int64";
    total_likes: "Int64";
    formula_version: "String";
    created_at: "DateTime";
    updated_at: "DateTime";
    fanbase_score: "Nullable(Float64)";
    engagement_score: "Nullable(Float64)";
  };
  instagram_cache: {
    account_id: "UInt32";
    snapshot_date: "Date";
    followers: "Int64";
    following: "Int64";
    media_count: "Int64";
    is_verified: "UInt8";
    is_business: "UInt8";
    category: "Nullable(String)";
    bio: "Nullable(String)";
    profile_pic_url: "Nullable(String)";
    external_url: "Nullable(String)";
    avg_likes_per_post: "Nullable(Float64)";
    avg_comments_per_post: "Nullable(Float64)";
    source: "String";
    provider: "String";
    s3_path: "String";
    job_id: "String";
    created_at: "DateTime";
  };
  l_cm_artist_tag: {
    id: "UInt64";
    cm_artist: "UInt32";
    tag: "UInt32";
    tag_type: "LowCardinality(String)";
    tag_slug: "String";
    source: "LowCardinality(String)";
    created_at: "DateTime";
  };
  l_profile_account: {
    id: "UInt32";
    profile_id: "UInt32";
    account_id: "UInt32";
    is_primary: "UInt8";
    connected_at: "DateTime";
    disconnected_at: "Nullable(DateTime)";
    created_at: "DateTime";
    modified_at: "DateTime";
  };
  profile: {
    id: "UInt32";
    name: "String";
    profile_type: "String";
    vertical: "String";
    image_url: "Nullable(String)";
    active: "String";
    created_at: "DateTime";
    cm_source_id: "Nullable(UInt64)";
    updated_at: "DateTime";
    cm_source: "LowCardinality(String)";
    cm_source_ref: "String";
    deleted_at: "Nullable(DateTime)";
    deleted_by: "Nullable(String)";
  };
  profile_snapshots: {
    id: "UInt64";
    profile_id: "UInt32";
    platform: "String";
    snapshot_date: "String";
    followers: "Nullable(Int64)";
    following: "Nullable(Int64)";
    posts: "Nullable(Int64)";
    likes: "Nullable(Int64)";
    engagement_rate: "Nullable(String)";
    verified: "Nullable(String)";
    bio: "Nullable(String)";
    display_name: "Nullable(String)";
    profile_pic_url: "Nullable(String)";
    raw_data: "Nullable(String)";
    created_at: "DateTime";
    updated_at: "DateTime";
  };
  tiktok_cache: {
    account_id: "UInt32";
    snapshot_date: "Date";
    follower_count: "Int64";
    following_count: "Int64";
    video_count: "Int64";
    heart_count: "Int64";
    is_verified: "UInt8";
    bio: "Nullable(String)";
    profile_pic_url: "Nullable(String)";
    source: "String";
    provider: "String";
    s3_path: "String";
    job_id: "String";
    created_at: "DateTime";
  };
}

// Type-safe record types for each table
export interface Athletes_cacheRecord {
  profile_id: number;
  name: string;
  type: string;
  is_active: number;
  sport: string;
  turned_pro_year: number | null;
  date_of_birth: string | null;
  nationality: string | null;
  nationality_continent: string | null;
  football_national_team: string | null;
  football_position: string | null;
  football_club: string | null;
  football_confederation: string | null;
  tennis_tour: string | null;
  tennis_ranking: number | null;
  tennis_playing_style: string | null;
  tennis_grand_slams: number | null;
  tennis_ranking_points: number | null;
  ig_account_id: number | null;
  ig_handle: string | null;
  ig_followers: string | null;
  ig_following: string | null;
  ig_posts: string | null;
  ig_verified: number | null;
  ig_engagement_rate: number | null;
  tiktok_account_id: number | null;
  tiktok_handle: string | null;
  tiktok_followers: string | null;
  tiktok_hearts: string | null;
  tiktok_videos: string | null;
  youtube_handle: string | null;
  youtube_followers: string | null;
  twitter_handle: string | null;
  twitter_followers: string | null;
  facebook_handle: string | null;
  facebook_followers: string | null;
  cm_score: number | null;
  cm_affinity: number | null;
  last_snapshot_date: string | null;
  created_at: string;
  modified_at: string;
  image_url: string | null;
  deleted_at: string | null;
}

export interface Cm_artistRecord {
  id: number;
  name: string;
  image_url: string;
  cover_url: string;
  code2: string;
  gender: number;
  isni: string;
  label: string;
  record_label: string;
  is_duplicate: number;
  band: number;
  is_non_artist: number;
  created_at: string | null;
  modified_at: string | null;
  synced_at: string;
}

export interface Cm_scoresRecord {
  id: string;
  profile_id: number;
  profile_type: string;
  score_date: string;
  cm_score: number;
  followers_score: number;
  likes_score: number;
  instagram_followers: string | null;
  instagram_likes: string | null;
  tiktok_followers: string | null;
  tiktok_likes: string | null;
  youtube_followers: string | null;
  twitter_followers: string | null;
  total_followers: string;
  total_likes: string;
  formula_version: string;
  created_at: string;
  updated_at: string;
  fanbase_score: number | null;
  engagement_score: number | null;
}

export interface Instagram_cacheRecord {
  account_id: number;
  snapshot_date: string;
  followers: string;
  following: string;
  media_count: string;
  is_verified: number;
  is_business: number;
  category: string | null;
  bio: string | null;
  profile_pic_url: string | null;
  external_url: string | null;
  avg_likes_per_post: number | null;
  avg_comments_per_post: number | null;
  source: string;
  provider: string;
  s3_path: string;
  job_id: string;
  created_at: string;
}

export interface L_cm_artist_tagRecord {
  id: string;
  cm_artist: number;
  tag: number;
  tag_type: string;
  tag_slug: string;
  source: string;
  created_at: string;
}

export interface L_profile_accountRecord {
  id: number;
  profile_id: number;
  account_id: number;
  is_primary: number;
  connected_at: string;
  disconnected_at: string | null;
  created_at: string;
  modified_at: string;
}

export interface ProfileRecord {
  id: number;
  name: string;
  profile_type: string;
  vertical: string;
  image_url: string | null;
  active: string;
  created_at: string;
  cm_source_id: string | null;
  updated_at: string;
  cm_source: string;
  cm_source_ref: string;
  deleted_at: string | null;
  deleted_by: string | null;
}

export interface Profile_snapshotsRecord {
  id: string;
  profile_id: number;
  platform: string;
  snapshot_date: string;
  followers: string | null;
  following: string | null;
  posts: string | null;
  likes: string | null;
  engagement_rate: string | null;
  verified: string | null;
  bio: string | null;
  display_name: string | null;
  profile_pic_url: string | null;
  raw_data: string | null;
  created_at: string;
  updated_at: string;
}

export interface Tiktok_cacheRecord {
  account_id: number;
  snapshot_date: string;
  follower_count: string;
  following_count: string;
  video_count: string;
  heart_count: string;
  is_verified: number;
  bio: string | null;
  profile_pic_url: string | null;
  source: string;
  provider: string;
  s3_path: string;
  job_id: string;
  created_at: string;
}

/**
 * Usage example:
 *
 * import { createQueryBuilder } from '@hypequery/clickhouse';
 * import { IntrospectedSchema } from './path-to-this-file';
 *
 * // Create a type-safe query builder
 * const db = createQueryBuilder<IntrospectedSchema>();
 *
 * // Now you have full type safety and autocomplete
 * const results = await db
 *   .table('athletes_cache')
 *   .select(['column1', 'column2'])
 *   .where('column1', 'eq', 'value')
 *   .execute();
 */
