import type { Athlete } from "../api/types";

export const buildAthlete = (overrides: Partial<Athlete> = {}): Athlete => ({
  age: 26,
  club: "Orlando Pride",
  cmScore: 87.4,
  gpsAtk: null,
  gpsDef: null,
  gpsScore: null,
  id: 1,
  igEngagementRate: null,
  igFollowers: 1_000_000,
  igPosts: 300,
  igVerified: false,
  imageUrl: null,
  lastMatchDate: null,
  leagues: [],
  level: "professional",
  momentumLabel: null,
  momentumScore: null,
  name: "Alex Morgan",
  nationality: "United States",
  nationalTeam: null,
  position: null,
  rank: 1,
  socialLinks: [],
  sport: "Football",
  teamLogoUrl: null,
  tiktokFollowers: null,
  tiktokHearts: null,
  tiktokLikes: null,
  tiktokPosts: null,
  tiktokVideos: null,
  turnedPro: null,
  ...overrides,
});
