/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/actors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    limit: number;
                    offset: number;
                    sortBy?: "instagramFollowers" | "name" | "popularity" | "roleCount";
                    sortDirection?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: number;
                                imageUrl: string | null;
                                instagramFollowers: number | null;
                                instagramHandle: string | null;
                                instagramUrl: string | null;
                                knownFor: {
                                    character: string | null;
                                    id: number;
                                    kind: string;
                                    name: string;
                                    network: string | null;
                                    popularity: number;
                                }[];
                                name: string;
                                popularity: number;
                                roleCount: number;
                            }[];
                            meta: {
                                limit: number;
                                offset: number;
                                total: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/artists/filter-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            countries: {
                                count: number;
                                value: string;
                            }[];
                            genres: {
                                count: number;
                                value: string;
                            }[];
                            instagramFollowers: {
                                max: number | null;
                                min: number | null;
                            };
                            tiktokFollowers: {
                                max: number | null;
                                min: number | null;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    limit: number;
                    offset: number;
                    changePeriod?: "1d" | "7d" | "28d";
                    countries?: string[];
                    excludeCountries?: string[];
                    excludeGenres?: string[];
                    genres?: string[];
                    maxInstagramFollowers?: number;
                    maxTiktokFollowers?: number;
                    minInstagramFollowers?: number;
                    minTiktokFollowers?: number;
                    name?: string;
                    sortBy?: "name" | "countryCode" | "cmScore" | "cmScoreChange" | "cmScoreChangePercent" | "instagramFollowers" | "instagramFollowersChange" | "instagramFollowersChangePercent" | "tiktokFollowers" | "tiktokFollowersChange" | "tiktokFollowersChangePercent";
                    sortDirection?: "asc" | "desc";
                    verifiedOnly?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                cmScore: number | null;
                                cmScoreChange: number | null;
                                cmScoreChangePercent: number | null;
                                countryCode: string | null;
                                id: number;
                                imageUrl: string | null;
                                instagramFollowers: number | null;
                                instagramFollowersChange: number | null;
                                instagramFollowersChangePercent: number | null;
                                isVerified: boolean;
                                name: string;
                                recordLabel: string | null;
                                tiktokFollowers: number | null;
                                tiktokFollowersChange: number | null;
                                tiktokFollowersChangePercent: number | null;
                            }[];
                            meta: {
                                limit: number;
                                offset: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/athletes/filter-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            clubsBySport: {
                                [key: string]: {
                                    [key: string]: string[];
                                };
                            };
                            cmScore: {
                                max: number | null;
                                min: number | null;
                            };
                            leaguesBySport: {
                                [key: string]: string[];
                            };
                            nationalities: {
                                count: number;
                                value: string;
                            }[];
                            sports: {
                                count: number;
                                value: string;
                            }[];
                            sportsByLevel: {
                                college: string[];
                                professional: string[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/athletes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    limit: number;
                    offset: number;
                    clubs?: string[];
                    excludeNationalities?: string[];
                    excludeSports?: string[];
                    leagues?: string[];
                    levels?: ("college" | "professional")[];
                    maxCmScore?: number;
                    maxFollowers?: number;
                    minCmScore?: number;
                    minFollowers?: number;
                    name?: string;
                    nationalities?: string[];
                    sortBy?: "cmScore" | "igFollowers" | "igPosts" | "name" | "nationality" | "rank" | "sport" | "tiktokFollowers" | "tiktokLikes";
                    /** @description Defaults to descending for metric columns and ascending for rank, name, nationality, sport and type. */
                    sortDirection?: "asc" | "desc";
                    sports?: string[];
                    verified?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                age: number | null;
                                club: string | null;
                                cmScore: number | null;
                                gpsAtk: number | null;
                                gpsDef: number | null;
                                gpsScore: number | null;
                                id: number;
                                igEngagementRate: number | null;
                                igFollowers: number | null;
                                igPosts: number | null;
                                igVerified: boolean;
                                imageUrl: string | null;
                                lastMatchDate: string | null;
                                leagues: string[];
                                level: "college" | "professional";
                                momentumLabel: string | null;
                                momentumScore: number | null;
                                name: string | null;
                                nationality: string | null;
                                nationalTeam: string | null;
                                position: string | null;
                                rank: number | null;
                                socialLinks: {
                                    handle: string;
                                    platform: string;
                                    url: string;
                                }[];
                                sport: string | null;
                                teamLogoUrl: string | null;
                                tiktokFollowers: number | null;
                                tiktokHearts: number | null;
                                tiktokLikes: number | null;
                                tiktokPosts: number | null;
                                tiktokVideos: number | null;
                                turnedPro: number | null;
                            }[];
                            meta: {
                                limit: number;
                                offset: number;
                                total: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: {
                    authorization?: string;
                    "x-org-id"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            account: {
                                id: string;
                                role: "owner" | "admin" | "analyst";
                            };
                            products: {
                                [key: string]: {
                                    enabled: boolean;
                                    features?: {
                                        [key: string]: unknown;
                                    };
                                };
                            };
                            user: {
                                id: string;
                            };
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message?: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message?: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Default Response */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message?: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/actors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    limit: number;
                    offset: number;
                    sortBy?: "instagramFollowers" | "name" | "popularity" | "roleCount";
                    sortDirection?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: number;
                                imageUrl: string | null;
                                instagramFollowers: number | null;
                                instagramHandle: string | null;
                                instagramUrl: string | null;
                                knownFor: {
                                    character: string | null;
                                    id: number;
                                    kind: string;
                                    name: string;
                                    network: string | null;
                                    popularity: number;
                                }[];
                                name: string;
                                popularity: number;
                                roleCount: number;
                            }[];
                            meta: {
                                limit: number;
                                offset: number;
                                total: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    limit: number;
                    offset: number;
                    changePeriod?: "1d" | "7d" | "28d";
                    countries?: string[];
                    excludeCountries?: string[];
                    excludeGenres?: string[];
                    genres?: string[];
                    maxInstagramFollowers?: number;
                    maxTiktokFollowers?: number;
                    minInstagramFollowers?: number;
                    minTiktokFollowers?: number;
                    name?: string;
                    sortBy?: "name" | "countryCode" | "cmScore" | "cmScoreChange" | "cmScoreChangePercent" | "instagramFollowers" | "instagramFollowersChange" | "instagramFollowersChangePercent" | "tiktokFollowers" | "tiktokFollowersChange" | "tiktokFollowersChangePercent";
                    sortDirection?: "asc" | "desc";
                    verifiedOnly?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                cmScore: number | null;
                                cmScoreChange: number | null;
                                cmScoreChangePercent: number | null;
                                countryCode: string | null;
                                id: number;
                                imageUrl: string | null;
                                instagramFollowers: number | null;
                                instagramFollowersChange: number | null;
                                instagramFollowersChangePercent: number | null;
                                isVerified: boolean;
                                name: string;
                                recordLabel: string | null;
                                tiktokFollowers: number | null;
                                tiktokFollowersChange: number | null;
                                tiktokFollowersChangePercent: number | null;
                            }[];
                            meta: {
                                limit: number;
                                offset: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/athletes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    limit: number;
                    offset: number;
                    clubs?: string[];
                    excludeNationalities?: string[];
                    excludeSports?: string[];
                    leagues?: string[];
                    levels?: ("college" | "professional")[];
                    maxCmScore?: number;
                    maxFollowers?: number;
                    minCmScore?: number;
                    minFollowers?: number;
                    name?: string;
                    nationalities?: string[];
                    sortBy?: "cmScore" | "igFollowers" | "igPosts" | "name" | "nationality" | "rank" | "sport" | "tiktokFollowers" | "tiktokLikes";
                    /** @description Defaults to descending for metric columns and ascending for rank, name, nationality, sport and type. */
                    sortDirection?: "asc" | "desc";
                    sports?: string[];
                    verified?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                age: number | null;
                                club: string | null;
                                cmScore: number | null;
                                gpsAtk: number | null;
                                gpsDef: number | null;
                                gpsScore: number | null;
                                id: number;
                                igEngagementRate: number | null;
                                igFollowers: number | null;
                                igPosts: number | null;
                                igVerified: boolean;
                                imageUrl: string | null;
                                lastMatchDate: string | null;
                                leagues: string[];
                                level: "college" | "professional";
                                momentumLabel: string | null;
                                momentumScore: number | null;
                                name: string | null;
                                nationality: string | null;
                                nationalTeam: string | null;
                                position: string | null;
                                rank: number | null;
                                socialLinks: {
                                    handle: string;
                                    platform: string;
                                    url: string;
                                }[];
                                sport: string | null;
                                teamLogoUrl: string | null;
                                tiktokFollowers: number | null;
                                tiktokHearts: number | null;
                                tiktokLikes: number | null;
                                tiktokPosts: number | null;
                                tiktokVideos: number | null;
                                turnedPro: number | null;
                            }[];
                            meta: {
                                limit: number;
                                offset: number;
                                total: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
