import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import {
  buildLiveSchema,
  diffSchema,
  formatDrift,
  type LiveColumnRow,
  parseSnapshotSchema,
  type SchemaDrift,
} from "../schema-drift.ts";

const PROFILE = "profile";
const SNAPSHOTS = "profile_snapshots";
const FOLLOWERS = "followers";
const FOLLOWERS_TYPE = "Nullable(Int64)";

const SNAPSHOT_SOURCE = `// Generated by @hypequery/clickhouse

export interface IntrospectedSchema {
  ${PROFILE}: {
    id: "UInt32";
    name: "String";
  };
  ${SNAPSHOTS}: {
    profile_id: "UInt32";
    ${FOLLOWERS}: "${FOLLOWERS_TYPE}";
  };
}

export interface ProfileRecord {
  id: number;
}
`;

const SNAPSHOT = parseSnapshotSchema(SNAPSHOT_SOURCE);

const LIVE_ROWS: readonly LiveColumnRow[] = [
  { name: "id", table: PROFILE, type: "UInt32" },
  { name: "name", table: PROFILE, type: "String" },
  { name: "profile_id", table: SNAPSHOTS, type: "UInt32" },
  { name: FOLLOWERS, table: SNAPSHOTS, type: FOLLOWERS_TYPE },
];

const driftAgainst = (rows: readonly LiveColumnRow[]): SchemaDrift =>
  diffSchema(SNAPSHOT, buildLiveSchema(rows));

const withoutColumn = (table: string, name: string): readonly LiveColumnRow[] =>
  LIVE_ROWS.filter((row) => row.table !== table || row.name !== name);

describe("parseSnapshotSchema", () => {
  it("reads every table, column, and type from the interface", () => {
    expect([...SNAPSHOT]).toEqual([
      [
        PROFILE,
        new Map([
          ["id", "UInt32"],
          ["name", "String"],
        ]),
      ],
      [
        SNAPSHOTS,
        new Map([
          ["profile_id", "UInt32"],
          [FOLLOWERS, FOLLOWERS_TYPE],
        ]),
      ],
    ]);
  });

  it("stops at the interface and ignores the record types below it", () => {
    expect(SNAPSHOT.has("ProfileRecord")).toBe(false);
    expect(SNAPSHOT.size).toBe(2);
  });

  it("normalizes whitespace inside a type literal", () => {
    const parsed = parseSnapshotSchema(
      'export interface IntrospectedSchema {\n  t: {\n    amount: "Decimal(18,   2)";\n  };\n}\n',
    );

    expect(parsed.get("t")?.get("amount")).toBe("Decimal(18, 2)");
  });

  it("rejects a source that declares no snapshot interface", () => {
    expect(() => parseSnapshotSchema("export interface Other {}\n")).toThrow(
      /declares no/,
    );
  });

  it("rejects a line that is neither a table nor a column", () => {
    expect(() =>
      parseSnapshotSchema(
        "export interface IntrospectedSchema {\n  t: {\n    id: number;\n  };\n}\n",
      ),
    ).toThrow(/not a column entry/);
  });

  it("rejects an interface that never closes", () => {
    expect(() =>
      parseSnapshotSchema(
        'export interface IntrospectedSchema {\n  t: {\n    id: "UInt32";\n  };\n',
      ),
    ).toThrow(/never closes/);
  });

  it("parses the committed snapshot, one table per generated record type", async () => {
    const committed = await readFile(
      fileURLToPath(new URL("../schema.generated.ts", import.meta.url)),
      "utf8",
    );
    const parsed = parseSnapshotSchema(committed);
    const recordTypes =
      committed.match(/^export interface \w+Record \{$/gm) ?? [];

    expect(parsed.size).toBe(recordTypes.length);
    for (const columns of parsed.values()) {
      expect(columns.size).toBeGreaterThan(0);
    }
  });
});

describe("diffSchema", () => {
  it("reports nothing when the warehouse matches the snapshot", () => {
    expect(driftAgainst(LIVE_ROWS)).toEqual({ additions: [], breaking: [] });
  });

  it("flags a changed column type as breaking", () => {
    const retyped = LIVE_ROWS.map((row) =>
      row.name === FOLLOWERS ? { ...row, type: "Int64" } : row,
    );

    expect(driftAgainst(retyped)).toEqual({
      additions: [],
      breaking: [
        {
          actual: "Int64",
          column: FOLLOWERS,
          expected: FOLLOWERS_TYPE,
          kind: "changed_type",
          table: SNAPSHOTS,
        },
      ],
    });
  });

  it("flags a vanished column as breaking", () => {
    expect(driftAgainst(withoutColumn(SNAPSHOTS, FOLLOWERS))).toEqual({
      additions: [],
      breaking: [
        {
          column: FOLLOWERS,
          expected: FOLLOWERS_TYPE,
          kind: "missing_column",
          table: SNAPSHOTS,
        },
      ],
    });
  });

  it("flags a vanished table once, not once per column", () => {
    const rows = LIVE_ROWS.filter((row) => row.table !== SNAPSHOTS);

    expect(driftAgainst(rows)).toEqual({
      additions: [],
      breaking: [{ kind: "missing_table", table: SNAPSHOTS }],
    });
  });

  it("reports a warehouse-only column without treating it as breaking", () => {
    const rows = [
      ...LIVE_ROWS,
      { name: "reach", table: SNAPSHOTS, type: FOLLOWERS_TYPE },
    ];

    expect(driftAgainst(rows)).toEqual({
      additions: [
        {
          actual: FOLLOWERS_TYPE,
          column: "reach",
          kind: "added_column",
          table: SNAPSHOTS,
        },
      ],
      breaking: [],
    });
  });

  it("ignores warehouse tables the snapshot does not cover", () => {
    const rows = [
      ...LIVE_ROWS,
      { name: "id", table: "unused", type: "UInt32" },
    ];

    expect(driftAgainst(rows)).toEqual({ additions: [], breaking: [] });
  });
});

describe("formatDrift", () => {
  it("says so when there is nothing to report", () => {
    expect(formatDrift(driftAgainst(LIVE_ROWS))).toBe(
      "Snapshot matches the warehouse.",
    );
  });

  it("names both sides of a type change", () => {
    const retyped = LIVE_ROWS.map((row) =>
      row.name === FOLLOWERS ? { ...row, type: "Int64" } : row,
    );
    const report = formatDrift(driftAgainst(retyped));

    expect(report).toContain("Breaking drift (1):");
    expect(report).toContain(
      `${SNAPSHOTS}.${FOLLOWERS} — snapshot ${FOLLOWERS_TYPE}, warehouse Int64`,
    );
  });

  it("separates warehouse-only columns from breaking drift", () => {
    const rows = [
      ...withoutColumn(PROFILE, "name"),
      { name: "reach", table: SNAPSHOTS, type: "UInt32" },
    ];
    const report = formatDrift(driftAgainst(rows));

    expect(report).toContain("Breaking drift (1):");
    expect(report).toContain("regenerate to pick these up (1):");
  });
});
